### ISSUE TITLE
Realistic mechanics of electricity

### ISSUE THREAD

**Issue by DenisWASD** [liquid600pgm/exCircuit#58]
## Description
It would work so that none of the electronic components would work if they are not connected to electricity.

**Comment by DenisWASD** [comment]
And don't tell me, that everbody can make it yourself. If you want to make this moddable, you should write an api for this.

**Comment by liquid600pgm** [comment]
That's what modding is for.
.
.
.
For real though, that could be implemented, but it would just be somewhat of a hassle: every power-producing device must've had a way of iterating through each device connected to a pin (which is possible without any problems), but the real hassle comes with power-consuming devices and the end user: they would have to connect *each* device with a battery. *Each*. **Each device**.

I'll look into that though, so this issue will stay open for the time being.

**Comment by liquid600pgm** [comment]
This will remain as an experimental feature and will have to be enabled with the `flag add devices.real_mode` command each time real mode should be used.

**Comment by liquid600pgm** [comment]
Implemented for r3.1 as an optional, experimental feature.
